# Generated by Django 4.0.6 on 2022-08-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
